### ISSUE TITLE
Sample for rendering Blazor sidebar in iFrame? 

### ISSUE THREAD

**Issue by taylorchasewhite** [mingyaulee/Blazor.BrowserExtension.Samples#4]
There is an allusion to rendering the sidebar inside an iframe, but I wasn't sure/able to figure out _how_ this is actually done. Would it be possible to show an example of that?

**Comment by mingyaulee** [comment]
Yes sure, the general idea is that in the content script you will need to render an iframe with the URL pointing to a page from your extension. Then you can style the container of the iframe so that it floats like a sidebar. I will try to find time to add the sample in the project some time in the next month when I can find time to do it.

**Comment by mingyaulee** [comment]
This is a year late as I have been extremely occupied with personal things, but the sample is finally up at https://github.com/mingyaulee/Blazor.BrowserExtension.Samples/tree/main/SidebarUsingIframe

Also, proper documentation for Blazor.BrowserExtension is now live at https://mingyaulee.github.io/Blazor.BrowserExtension/
