### ISSUE TITLE
Example with hot reload using ContentScript/Iframe (Chrome)

### ISSUE THREAD

**Issue by bukowa** [mingyaulee/Blazor.BrowserExtension.Samples#5]
Hey! I wonder if someone can provide an example of hot reload when running `dotnet watch`. Specifically, how to make it so the content script on a webpage would be reloaded without reloading the webpage?

**Comment by mingyaulee** [comment]
Unfortunately, hot reload does not work when running the app is loaded as an extension, instead of debugging. This is because hot reload requires the app to be communicating with dotnet watch, but right now, no external communication is being established when the app is loaded as extension in the browser.
